<script>
    var label_please_wait = '<?= get_label('please_wait', 'Please wait...') ?>';
    var label_please_select_records_to_delete = '<?= get_label('please_select_records_to_delete', 'Please select records to delete.') ?>';
    var label_something_went_wrong = '<?= get_label('something_went_wrong', 'Something went wrong.') ?>';
    var label_please_correct_errors = '<?= get_label('please_correct_errors', 'Please correct errors.') ?>';
    var label_project_removed_from_favorite_successfully = '<?= get_label('project_removed_from_favorite_successfully', 'Project removed from favorite successfully.') ?>';
    var label_project_marked_as_favorite_successfully = '<?= get_label('project_marked_as_favorite_successfully', 'Project marked as favorite successfully.') ?>';
    var label_yes = '<?= get_label('yes', 'Yes') ?>';
    var label_upload = '<?= get_label('upload', 'Upload') ?>';
    var decimal_points = <?= intval($general_settings['decimal_points_in_currency'] ?? '2') ?>;
    var label_update = '<?= get_label('update', 'Update') ?>';
    var label_delete = '<?= get_label('delete', 'Delete') ?>';
    var label_view = '<?= get_label('view', 'View') ?>';
    var label_not_assigned = '<?= get_label('not_assigned', 'Not assigned') ?>';
    var label_delete_selected = '<?= get_label('delete_selected', 'Delete selected') ?>';
    var label_search = '<?= get_label('search', 'Search') ?>';
    var label_create = '<?= get_label('create', 'Create') ?>';
    var label_users_associated_with_project = '<?= get_label('users_associated_with_project', 'Users associated with project') ?>';
    var label_update_task = '<?= get_label('update_task', 'Update Task') ?>';
    var label_quick_view = '<?= get_label('quick_view', 'Quick View') ?>';
    var label_project = '<?= get_label('project', 'Project') ?>';
    var label_task = '<?= get_label('task', 'Task') ?>';
    var label_projects = '<?= get_label('projects', 'Projects') ?>';
    var label_tasks = '<?= get_label('tasks', 'Tasks') ?>';
    var label_clear_filters = '<?= get_label('clear_filters', 'Clear Filters') ?>';
    var label_set_as_default_view = '<?= get_label('set_as_default_view', 'Set as Default View') ?>';
    var label_default_view = '<?= get_label('default_view', 'Default View') ?>';
    var label_save_column_visibility = '<?= get_label('save_column_visibility', 'Save Column Visibility') ?>';
    var label_showing = '<?= get_label('showing', 'Showing') ?>';
    var label_to_for_pagination = '<?= get_label('to_for_pagination', 'to') ?>';
    var label_of = '<?= get_label('of', 'of') ?>';
    var label_rows = '<?= get_label('rows', 'rows') ?>';
    var label_rows_per_page = '<?= get_label('rows_per_page', 'rows per page') ?>';
    var label_select = '<?= get_label('select', 'Select') ?>';
    var label_or = '<?= get_label('or', 'or') ?>';
    var label_drag_and_drop_files_here = '<?= get_label('drag_and_drop_files_here', 'Drag & Drop Files Here') ?>';
    var label_drag_and_drop_update_zip_here = "<?= get_label('drag_and_drop_update_zip_here', 'Drag & Drop System Update / Installable / Plugin\'s .zip file Here') ?>";
    var label_only_one_file_can_be_uploaded_at_a_time = "<?= get_label('only_one_file_can_be_uploaded_at_a_time', 'Only 1 file can be uploaded at a time') ?>";
</script>